# Generated by Django 2.0.3 on 2018-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
