# Generated by Django 2.0.3 on 2018-04-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoisin', '0002_auto_20180409_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
